### ISSUE TITLE
ImportError: No module named 'fused'

### ISSUE THREAD

**Issue by kfcvme666** [sigal-raab/MoDi#1]
(MoDi) jijiahui@ubuntu:~/MoDi$ python generate.py --type sample --motions 18 --ckpt ./data/ckpt.pt --out_path ./output --path ./data/edge_rot_data.npy
Traceback (most recent call last):
  File "generate.py", line 13, in <module>
    from utils.pre_run import GenerateOptions, load_all_form_checkpoint
  File "/data/home/jijiahui/MoDi/utils/pre_run.py", line 5, in <module>
    from models.gan import Generator, Discriminator
  File "/data/home/jijiahui/MoDi/models/gan.py", line 16, in <module>
    from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/data/home/jijiahui/MoDi/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/data/home/jijiahui/MoDi/op/fused_act.py", line 18, in <module>
    build_directory=os.path.join(os.path.expanduser('~'),'tmp', 'stylegan_lock'),
  File "/data/home/jijiahui/miniconda3/envs/MoDi/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 898, in load
    is_python_module)
  File "/data/home/jijiahui/miniconda3/envs/MoDi/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1097, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/data/home/jijiahui/miniconda3/envs/MoDi/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1418, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/data/home/jijiahui/miniconda3/envs/MoDi/lib/python3.6/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'fused'

**Comment by sigal-raab** [comment]
@kfcvme666, there may be several reasons for this issue, all related to package versions.
In [this link](https://github.com/yuval-alaluf/SAM/issues/35#issuecomment-918308249), the solution was to set Cuda to 11.3 and Pytorch to 1.9. 
In [this link](https://github.com/rosinality/stylegan2-pytorch/issues/1#issuecomment-1186088761) the solution was to set the GCC version to either 7.5.0 or 5.2.0.
[This link](https://github.com/rosinality/stylegan2-pytorch/issues/1) offers more solution directions.
Note that the MoDi's equivalent to the folder ~/.cache/torch_extensions/fused (mentioned in the aforementioned solutions), is $Home/mp/stylegan_lock.

Let me know if this helped.

**Comment by kfcvme666** [comment]
> Thank you very much for your help, but then I encountered a new problem：

(MoDi) jijiahui@ubuntu:~/MoDi$ python generate.py --type sample --motions 18 --ckpt ./data/ckpt.pt --out_path ./output --path ./data/edge_rot_data.npy
Traceback (most recent call last):
  File "generate.py", line 13, in <module>
    from utils.pre_run import GenerateOptions, load_all_form_checkpoint
  File "/data/home/jijiahui/MoDi/utils/pre_run.py", line 5, in <module>
    from models.gan import Generator, Discriminator
  File "/data/home/jijiahui/MoDi/models/gan.py", line 16, in <module>
    from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/data/home/jijiahui/MoDi/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/data/home/jijiahui/MoDi/op/fused_act.py", line 18, in <module>
    build_directory=os.path.join(os.path.expanduser('~'),'tmp', 'stylegan_lock'),
  File "/data/home/jijiahui/miniconda3/envs/MoDi/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1092, in load
    keep_intermediates=keep_intermediates)
  File "/data/home/jijiahui/miniconda3/envs/MoDi/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1318, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/data/home/jijiahui/miniconda3/envs/MoDi/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1701, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: /data/home/jijiahui/tmp/stylegan_lock/fused.so: cannot open shared object file: No such file or directory

so where's 'fused.so'?

**Comment by sigal-raab** [comment]
Sadly, this is a problem we 'inherited' from the stylegan code, and requires trial and error with package versions.
The solutions are different for each machine.

Here is what worked for us on Cuda 11.5, after some trials and errors. I hope it will work for you if you are using Cuda 11.5 or similar. If you are using a different Cuda version, it may hint at a direction.
Let me know if you succeeded.

Python 3.7.16

# torch 1.7.1
conda install pytorch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 cudatoolkit=11.0 -c pytorch

# cuda_11.3.r11.3
conda install -c "nvidia/label/cuda-11.3.1" cuda-toolkit

# gcc (GCC) 6.1.0 
conda install -c omgarcia gcc-6

# Ninja
conda install -c conda-forge ninja

ו

**Comment by sigal-raab** [comment]
I am closing the issue. Feel free to reopen it if needed.
